/* prettier-ignore */
export const keys = {
  aboutUs:                                                   ['ABOUT_US'] as const,
  watchUser:                                                 ['WATCH_USER'] as const,
  auth:                                                      ['AUTH_DATA'] as const,
  blogs:                                                     ['BLOGS'],
  bookings:                                                  ['BOOKINGS'] as const,
  bookingsMasks:                                             ['BOOKINGS_MASKS'] as const,
  claims:                                                    ['CLAIMS'] as const,
  content:                                                   ['CONTENT'],
  countries:                                                 ['COUNTRIES'] as const,
  exchange:                                                  ['EXCHANGE_RATES'] as const,
  payments:                                                  ['PAYMENTS'] as const,
  shipments:                                                 ['SHIPMENTS'] as const,
  supportRequests:                                           ['SUPPORT_REQUESTS'] as const,
  airports:          (city?: string)                      => ['AIRPORTS', city] as const,
  blog:              (id: string)                         => ['BLOG', id] as const,
  chat:              (chatId?: string)                    => ['CHAT_ID', chatId] as const,
  chatId:            (assign?: string, assignId?: string) => ['CHAT_ID', assign, assignId] as const,
  cities:            (country?: string)                   => ['CITIES', country] as const,
  claim:             (id: string)                         => ['CLAIM', id] as const,
  load:              (id: string)                         => ['LOAD', id] as const,
  loadOffers:        (id: string, status?: string)        => ['LOAD_OFFERS', id, status] as const,
  loads:             (status?: string)                    => ['LOADS', status] as const,
  ports:             (country?: string)                   => ['PORTS', country] as const,
  shipment:          (id: string)                         => ['SHIPMENT', id] as const,
  supportRequest:    (id: string)                         => ['SUPPORT_REQUEST', id] as const,
  deliveryLocations: (id: string)                         => ['DELIVERY_LOCATIONS', id] as const,
};
